name: C:\Anaconda3\envs\makeorbreak
dependencies:
- flask=0.10.1=py35_1
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_1
- pip=8.1.1=py35_1
- python=3.5.1=4
- setuptools=20.3=py35_0
- sqlalchemy=1.0.12=py35_0
- vs2015_runtime=14.00.23026.0=0
- werkzeug=0.11.5=py35_0
- wheel=0.29.0=py35_0
- pip:
  - clarifai==0.2.1
  - decorator==4.0.9
  - flask-sqlalchemy==2.1
  - httplib2==0.9.2
  - pbr==1.8.1
  - pysocks==1.5.6
  - pytz==2016.3
  - requests==2.9.1
  - six==1.10.0
  - sqlalchemy-migrate==0.10.0
  - sqlparse==0.1.19
  - tempita==0.5.2
  - tinys3==0.1.11
  - twilio==5.4.0

